### ISSUE TITLE
:sparkles: Add an example contract to validate `DaoActionData`

### ISSUE THREAD

**Issue by doitian** [cryptape/ckb-dao-cobuild-poc#23]
- [x] setup contract development env #28
- [x] generate schema rust code for contract #29 
- [x] dao action data schema validation #36
- [x] coverage: all operations in tx can be found in action. `DerivedDaoActionData#complete`
- [x] withdraw #38
- [x] claim from #40 
- [x] deposit to #37
- [x] deposit from: allow deposit from any input cells except dao deposit cells #41 
- [x] claim to: allow claim to any input cells except dao withdraw cells #41

## Architecture

`DerivedDaoActionData` is responsible to verify deposit to, withdraw and claim from

- Derive dao operations from tx `DerivedDaoActionData#derive`
- Verify that the derived operations can be found in the CoBuild message, and there are now two derived operations mapping to the same operation in the CoBuild message. `DerivedDaoActionData#verify`
- Verify that all derived operations can be found. `DerivedDaoActionData#complete`

`DerivedCkbAccounting` is responsible to verify deposit from and claim to

- Accumulate accounting requirements from CoBuild message `DerivedCkbAccounting#derive`
- Tally the CKB balance in tx and verify the account balances are sufficient `DerivedCkbAccounting#verify`
